repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--color  
          - --args=--minimum-failure-severity=warning
          - --args=--enable-rule=terraform_documented_variables
        files: (\.tf|\.tfvars)$
        exclude: (\.terraform.*|^example/complete/[^/]+)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
